// Auto-generated by scripts/generate-blog-index.mjs
export const blogPosts = [
  {
    "id": "b2",
    "title": "The Complete Guide to Building a Gaming PC in Vadodara",
    "category": "PC Building",
    "excerpt": "Parts selection, budgeting, cooling and assembly tips for your first custom gaming rig.",
    "date": "2026-07-08T00:00:00.000Z",
    "readTime": "8 min read",
    "slug": "building-a-gaming-pc",
    "html": "Building a gaming PC can be fun. Start with a budget, pick CPU and GPU, and focus on cooling.\n\n* Choose parts that match your target resolution and framerate.\n* Ensure PSU has headroom.\n* Don't forget cable management.\n"
  },
  {
    "id": "b1",
    "title": "How AI Chatbots Are Transforming Small Business Lead Capture",
    "category": "AI",
    "excerpt": "Why 24/7 automated responses are the highest-ROI upgrade for service businesses in 2026.",
    "date": "2026-07-12T00:00:00.000Z",
    "readTime": "5 min read",
    "slug": "how-ai-chatbots-transform-lead-capture",
    "html": "AI chatbots help businesses capture leads around the clock. Here's a quick overview of why they're effective:\n\n* Available 24/7\n* Qualify leads automatically\n* Reduce human workload\n\nMore details coming soon.\n"
  }
];
